language: cpp

addons:
  sonarcloud:
    organization: "luokung" # the key of the org you chose at step #3
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token

branches:
  only:
  - master
  
before_install:
  - pip install --user cpp-coveralls
  
script:
  - g++ main.cpp -o hello -coverage
  - ./hello
  - sonar-scanner
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
