language: cpp
sudo: required

services:
  - docker

addons:
  sonarcloud:
    organization: "luokung" # the key of the org you chose at step #3
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token

branches:
  only:
  - master
  
before_install:
  - pip install --user cpp-coveralls
  
script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output g++ main.cpp -o hello -coverage
  - ./hello
  - sonar-scanner
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
  # test docker build
  - docker build -t cpp_cd .
  # docker push to registy
  