language: cpp

branches:
  only:
  - master
  
before_install:
  - pip install --user cpp-coveralls
  
script:
  - g++ main.cpp -o hello -coverage
  - ./hello
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
